# Generated by Django 5.0.1 on 2024-06-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0026_crmcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatioOfProjectsFromWRToSZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('project_id', models.BigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WantResultContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.IntegerField(blank=True)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('page', models.CharField(blank=True, max_length=255)),
                ('ref', models.CharField(blank=True, max_length=255)),
                ('time', models.DateTimeField(blank=True, max_length=255)),
                ('browser', models.CharField(blank=True, max_length=255)),
                ('device', models.CharField(blank=True, max_length=255)),
                ('platform', models.CharField(blank=True, max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('roistat_visit', models.CharField(blank=True, max_length=255)),
                ('phones_first', models.CharField(blank=True, max_length=255)),
                ('phones_second', models.CharField(blank=True, max_length=255)),
                ('phones_third', models.CharField(blank=True, max_length=255)),
                ('mails_first', models.CharField(blank=True, max_length=255)),
                ('mails_second', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('gclid', models.CharField(blank=True, max_length=255)),
                ('project_id', models.BigIntegerField(blank=True)),
            ],
        ),
    ]
