# Generated by Django 5.0.1 on 2024-06-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0027_ratioofprojectsfromwrtosz_wantresultcontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantresultcontacts',
            name='time',
            field=models.BigIntegerField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='wantresultcontacts',
            name='vid',
            field=models.BigIntegerField(blank=True),
        ),
    ]
